---
global:
  scrape_interval: 15s

scrape_configs:
- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080
    labels:
      ownedby: 'ashli'

- job_name: node-exporter
  static_configs:
  - targets: ['65.2.128.68:9100']
    labels:
      ownedby: 'ashli'
